### PR TITLE
feat: Multi-selection and installation 

### PR DESCRIPTION
**Pull request by jeevithakannan2**
**This PR is replaced with https://github.com/ChrisTitusTech/linutil/pull/338**

### CODE REVIEW

**Comment by guruswarupa** [comment]
@jeevithakannan2 squash those commits to 1 as its just 1 feature your working on.

**Comment by jeevithakannan2** [comment]
When merging it will be squashed automatically right?

**Comment by guruswarupa** [comment]
> When merging it will be squashed automatically right?

better to keep the git log clean :)

**Comment by jeevithakannan2** [comment]
Ok

**Pull request closed without merging**
