### PR TITLE
docs: automated dynamic gif previews using `vhs`

### PR DESCRIPTION
**Pull request by adamperkowski**
## Type of Change
- [x] Documentation update

## Description
This is auto-generated on every release. Feel free to ask me about the changes (why? how? why not...?) or suggest your changes to the `tape` file.

FYI I tried doing this in a different workflow and then calling it from the release one (that's obviously better) but I've encountered some issues like the runner not shipping the right version of `glibc` to run linutil. A headache.

## Preview of a preview (a bit outdated, i added a delay before confirming the launch)
preview

## Testing
https://github.com/adamperkowski/linutil/actions/runs/11149279338/job/30987803438

## Issues / other PRs related
Conflicts with (more like a different option) #730.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by cartercanedy** [comment]
Nice! Well done

**Comment by nnyyxxxx** [comment]
should we do the gif instead of the logo

**Comment by adamperkowski** [comment]
@nnyyxxxx I don't know. That's why I opened this PR. If you decide to close #730, I'll push your README commits here.

**Comment by nnyyxxxx** [comment]
> @nnyyxxxx I don't know. That's why I opened this PR. If you decide to close #730, I'll push your README commits here.

nah its fine, atleast Chris has the option between gif and logo

**Comment by cartercanedy** [comment]
> nah its fine, atleast Chris has the option between gif and logo

why not both?

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
