### PR TITLE
using reflector

### PR DESCRIPTION
**Pull request by dhruvmistry2000**
## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

I used rate mirror but every time I used it it used erased the mirrorlist from /etc/pacman.d/mirrorlist 

## Issues / other PRs related

- Resolves #
- Cleaing of sources.list in ARCH

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — CHANGES_REQUESTED** [review]
Please test your changes before submitting.
image

**Review by jeevithakannan2 — CHANGES_REQUESTED** [review]
There shouldn't be any issues with mirror generation, can you post the output of system update and `cat /etc/pacman.d/mirrorlist` after running the system update.

And the parameters are wrong for reflector

**Comment by dhruvmistry2000** [comment]
I will see to it but everytime i use rate-mirror it wipes the mirrors list butbi will check the parameters

**Comment by dhruvmistry2000** [comment]
I dont know how it word now so i am closing the request

**Pull request closed without merging**
