### PR TITLE
fix: Add missing nala

### LINKED ISSUE #543: Docker not installing
## Describe the bug
Docker is not installing I'm on Debian, and I get package manager not supported

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [x] Bug fix

## Description
- Added missing nala in scripts

## Testing
- Tested on debian12 works fine

## Issues / other PRs related
- Resolves #543 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — COMMENTED** [review]
These shouldn't be quoted. Include unquoting in this PR pls.
https://github.com/ChrisTitusTech/linutil/blob/93ac1064d4fd9664365592cd69447f5fd590936e/tabs/system-setup/5-samba-ssh-setup.sh#L29-L33

**Comment by jeevithakannan2** [comment]
> These shouldn't be quoted. Include unquoting in this PR pls.
> 
> https://github.com/ChrisTitusTech/linutil/blob/93ac1064d4fd9664365592cd69447f5fd590936e/tabs/system-setup/5-samba-ssh-setup.sh#L29-L33

Yup sorry didn't notice it was there !!

**Review by adamperkowski — APPROVED** [review]
Thanks!

**Review by ChrisTitusTech — APPROVED** [review]
Update with new merges as we changed file names

**Comment by jeevithakannan2** [comment]
@ChrisTitusTech Ready for merge !!!

**Review by adamperkowski — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
