### PR TITLE
Add description to the System Setup section

### PR DESCRIPTION
**Pull request by CarsBeck**
## Type of Change
- [x] UI/UX improvement

## Description

I added a description to the Full System Cleanup command in the System Setup section.

## Testing

I built and ran the application, ensuring the description displayed as intended.

## Impact

Descriptions are now available for commands that previously did not include them, which adds more context to inexperienced users.

## Issues / other PRs related

- Improves the UI and the UX

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — CHANGES_REQUESTED** [review]
what about these?
https://github.com/ChrisTitusTech/linutil/blob/2082797e6e9418635b428497b3d65d493a91d9b7/core/tabs/system-setup/tab_data.toml#L44-L52

**Comment by CarsBeck** [comment]
> what about these?
> 
> https://github.com/ChrisTitusTech/linutil/blob/2082797e6e9418635b428497b3d65d493a91d9b7/core/tabs/system-setup/tab_data.toml#L44-L52

I am blind and will change this, is there anything I need to mark on the post in the meantime to signify I'm changing it?

**Comment by CarsBeck** [comment]
Should be good now, thanks for the catch (I'm new to all this)

**Review by adamperkowski — APPROVED** [review]
No problem. We've all been there.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
