### PR TITLE
Change apt-get's & use nala along with apt

### PR DESCRIPTION
**Pull request by nnyyxxxx**
# Merge with #442 #443 #454

## Type of Change
- [x] New feature
- [x] Refactoring

## Description
#422 does this slightly correct; I have added the missing ones that weren't included in his PR

Gaming-setup & Aur helpers were skipped due to #382 and #380 which include refactoring for both of these functionality

ONLY after I made my 3 PRs did he decide to implement MY fixes.. before: https://github.com/ChrisTitusTech/linutil/commit/61cddeb2566f0c874c15428986381832203f3591 after: https://github.com/ChrisTitusTech/linutil/commit/100fc58daa91b127187497f0061922786747db0d

My commits are VERIFIED, meaning everything that I do contains MY work. Take a look at these 2 commits and decide for your self. The first commit contained INCOMPLETE functionality and only after making my 3 PRs that fixed those issues did he decide to grab the changes in my commits and then implement them in his.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — APPROVED** [review]

**Comment by jeevithakannan2** [comment]
@ChrisTitusTech 

> [!CAUTION]
> This PR is not tested.
> This implementation is wrong and will not use nala.
> Changing apt-get with apt is not recommended when running scripts

**Comment by nnyyxxxx** [comment]
> Changing apt-get with apt is not recommended when running scripts

This PR is tested. Using apt instead of apt-get is better as it's newer and more developed: apt-get is old and will deprecate eventually, Nala will work; as this is already implemented some-what in the existing scripts.

**Comment by nnyyxxxx** [comment]
Your criticism is not appreciated when you copied my whole implementation into YOUR PR, and DID not give credit.. Unlike you I REWROTE everything. Here are the commits on your PR if needed: before: https://github.com/ChrisTitusTech/linutil/commit/61cddeb2566f0c874c15428986381832203f3591 after: https://github.com/ChrisTitusTech/linutil/commit/100fc58daa91b127187497f0061922786747db0d

**Comment by nnyyxxxx** [comment]
image

Here is Adam's input on these PRs

**Comment by adamperkowski** [comment]
@jeevithakannan2 

> This PR is not tested.

You have no way of knowing this.

> This implementation is wrong and will not use nala.

?? https://github.com/ChrisTitusTech/linutil/pull/422#issuecomment-2355774644

> Changing apt-get with apt is not recommended when running scripts

I already proved you wrong in https://github.com/ChrisTitusTech/linutil/pull/422#issuecomment-2355774644.

**Comment by adamperkowski** [comment]
I think #440 #442 #443 approach this better. #422 is clearly copying the changes from them into his own implementation.

**Comment by ChrisTitusTech** [comment]
For scripting apt-get will be used.

**Pull request closed without merging**
