### PR TITLE
implement dynamic shortcut list sizing

### LINKED ISSUE #653: Command List cuts off - Needs 3 Lines
## Describe the bug
Command list is too long and doesn't always display the shortcut keys

## To Reproduce
Run at 1920x1080

## Screenshots
image

## Checklist
- [x] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by cartercanedy**
## Type of Change
- [x] Bug fix

## Description
Makes shortcut list dynamically sized

## Issues / other PRs related

- Resolves #653 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
image
might wanna organize these into a grid like pattern so they dont look messy

**Comment by cartercanedy** [comment]
Good idea, that'll be a little bit longer to get implemented right, though, so this'll at least get the bug sorted

**Review by adamperkowski — APPROVED** [review]
awesome

**Comment by cartercanedy** [comment]
Any feedback @lj3954?

**Review by ChrisTitusTech — APPROVED** [review]
Fantastic! Was just thinking about this a couple days ago on a smaller screen.

**Pull request merged**
