### PR TITLE
implement word wrapping functionality

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] New feature

## Description
adds dynamic / auto updating word wrapping to the descriptions

### CODE REVIEW

**Review by adamperkowski — APPROVED** [review]
Looks OK from a first glance.

**Comment by afonsofrancof** [comment]
I removed the FloatingTextMode a few days ago, so we can use any title we want.
Maybe it's better to have the new() function receive a boolean telling it if it should wrap the words, and we only activate that on the description for now.
It would then be very easy to activate it in the future for other float types

**Comment by nnyyxxxx** [comment]
> > that's already implemented via enum rather than boolean
> 
> Yes, I know, that enum existed a few days ago, and it was removed to make the float more generic, so that the title can be anything instead of just those 3 enum types.
> 
> That's why I was saying that a boolean is better.

oh i didnt notice

**Review by adamperkowski — APPROVED** [review]

**Review by afonsofrancof — APPROVED** [review]
lgtm

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
