### PR TITLE
[WIP] Added support for riscv64 based devices

### PR DESCRIPTION
**Pull request by Umeaboy**
## Type of Change
- [X] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
I see that riscv64 support isn't there.

## Testing
No testing has been done as I don't own a device with a RISCV based processor.

## Impact
No bigger impact.

## Issues / other PRs related
No issues.

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by adamperkowski** [comment]
@Umeaboy Draft the PR if it's WIP.

**Comment by Umeaboy** [comment]
> Draft the PR

Draft? You mean summarize it?

**Comment by adamperkowski** [comment]
> Draft? You mean summarize it?

image

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by adamperkowski** [comment]
@Umeaboy click "Convert to draft"

**Comment by Umeaboy** [comment]
> @Umeaboy click "Convert to draft". You have to reopen first.

If I'm not mistaken, nobody but @ChrisTitusTech can reopen closed PR's.

**Comment by adamperkowski** [comment]
> If I'm not mistaken, nobody but @ChrisTitusTech can reopen closed PR's.

You are mistaken. Only the user who closes a PR (or has write access) can reopen it.

**Comment by adamperkowski** [comment]
Just open a new one. And make it a draft PR.

**Comment by Umeaboy** [comment]
And @Titus Tech Talk closed it.
Hence meaning that I can't reopen it no matter how much I would like to.
/Kristoffer

19 sep. 2024 22:00 av ***@***.***:

**Pull request closed without merging**
