### PR TITLE
fix global theming

### LINKED ISSUE #165: Global Theme doesn't apply everywhere
## Describe the bug
after applying "Global Dark Theme" KDE Settings is in light mode

## To Reproduce
open KDE Settings

## Expected behavior
KDE Settings to be in dark mode

## Screenshots
image

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] Bug fix

## Description
- fixes KDE' theming being bricked
- Adds actual theming for specific DE's

## Testing
tested
image

## Issues / other PRs related

- Resolves #165 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — APPROVED** [review]

**Comment by GreatNovaDragon** [comment]
This is a terrible fix cause 

a) it doesnt actually fix what causes this, and 
b) instead reverts everything that the script does by overwriting it with the KDE settings. 

Kvantum may get configured, but then straight up gets ignored cause the themeing is set away from Kvantum to breeze-dark

**Comment by GreatNovaDragon** [comment]
this still leaves non-KDE theme-ing broken with that.

**Comment by nnyyxxxx** [comment]
the fix is fine, i'm going to re-write it for my sanity though

**Comment by GreatNovaDragon** [comment]
Wouldn't be fixed yet.

The big intention of the script is "Applications should use a consistent global theme"

The script before the pr says "QT apps should use the theme the qt6 controll center tells it to use" and then sets qt6ct to say "use whatever kvantum says" and then tells kvantum "Use Breeze"
There is no Breeze kvantum theme. There also will never be one.

On QT Apps, this is also multiple steps to many, cause you can tell it directly "use breeze" instead. Would fix an issue, even though generally in KDE/QT Theming loves to use kvantum. 

It also completly ignores that GTK exists. For GTK, breeze-gtk exists in an official capability, so that could just be used there too. Yay for consistent themeing, which this script wants to achieve. 


The script after the pr says 

"Yeah, set up all the faulty stuff, but if we use KDE, throw out everything and use breeze-dark, and if we use Gnome, still use the faulty stuff in QT applications, and GTK may use adwaita-dark"

**Comment by nnyyxxxx** [comment]
> Wouldn't be fixed yet.
> 
> The big intention of the script is "Applications should use a consistent global theme"
> 
> The script before the pr says "QT apps should use the theme the qt6 controll center tells it to use" and then sets qt6ct to say "use whatever kvantum says" and then tells kvantum "Use Breeze" There is no Breeze kvantum theme. There also will never be one.
> 
> On QT Apps, this is also multiple steps to many, cause you can tell it directly "use breeze" instead. Would fix an issue, even though generally in KDE/QT Theming loves to use kvantum.
> 
> It also completly ignores that GTK exists. For GTK, breeze-gtk exists in an official capability, so that could just be used there too. Yay for consistent themeing, which this script wants to achieve.
> 
> The script after the pr says
> 
> "Yeah, set up all the faulty stuff, but if we use KDE, throw out everything and use breeze-dark and ignore gtk, and if we use Gnome, still use the faulty stuff in QT applications, and GTK may use adwaita-dark"

wait till you find out you cant directly set kde's dark theme without ``lookandfeeltool``

**Comment by GreatNovaDragon** [comment]
it doesnt fix global themeing though. It fixes themeing in KDE and adds an half-measure for gnome.

**Comment by nnyyxxxx** [comment]
> it doesnt fix global themeing though. It fixes themeing in KDE and adds an half-measure for gnome.

again, i'm re-writing the fix to quell your concerns. Gnome is fine how it is, as it uses gtk for mostly everything.

The issue with kvantum and qt6ct will be fixed in the next commit :ok_hand:

**Comment by GreatNovaDragon** [comment]
The commit doesnt fix that, it just reorders stuff. 

The solution would probably be to not install kvantum at all, and tell qt6ct to use breeze-dark where it is told to use kvantum.

**Comment by nnyyxxxx** [comment]
> The commit doesnt fix that, it just reorders stuff.
> 
> The solution would probably be to not install kvantum at all, and tell qt6ct to use breeze-dark where it is told to use kvantum.

the commit fixes everything. not sure where your concerns are?

**Comment by GreatNovaDragon** [comment]
my concern is that Kvantum does NOT have a breeze theme and still sets that.

**Comment by nnyyxxxx** [comment]
if you're on kde or gnome the rest does not get ran, likewise if you're on any other DE the rest does get ran. More DE's can be added in the future.

**Comment by GreatNovaDragon** [comment]
dwm-titus is an explicit thing that gets installed by linutil, dwm-titus is dependant on that fix

**Comment by GreatNovaDragon** [comment]
yeah, that works too.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
