### PR TITLE
❄️ nix (and nixos) support

### LINKED ISSUE #759: ❄️ nix & nixos support
## Description
I could start working on official support for nixos (`.nix` linutil package & compatibility).
That includes supporting nix package manager in existing scripts.

I need input about this though. Do we **want** nix support?

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

### PR DESCRIPTION
**Pull request by adamperkowski**
## Type of Change
- [x] New feature
- [x] Refactoring

## Issues / other PRs related
- Resolves #759

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
Don't forget to modify the configuration.nix for services.

`services.flatpak.enable = true;` for flatpak

**Comment by adamperkowski** [comment]
> Don't forget to modify the configuration.nix for services.
> 
> `services.flatpak.enable = true;` for flatpak

I know. I am working on this right now.

**Comment by adamperkowski** [comment]
I'm hitting kind of a road block here. We need to modify the nix configuration file but there is no parser available. Help is more than welcome.

**Comment by adamperkowski** [comment]
Closing this for now.
image

**Pull request closed without merging**
