### PR TITLE
Restore behaviour of closing the pop-up with "q"

### PR DESCRIPTION
**Pull request by afonsofrancof**
I am so used to pressing q to quit everything.
I remember using it a lot, is there a reason as to why it was removed?
LTM if this is not desired behaviour.

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
Yeah I was thinking the same but I think it was not added in the first place. Anyways love this change

**Review by adamperkowski — APPROVED** [review]

**Review by lj3954 — APPROVED** [review]

**Comment by cartercanedy** [comment]
this was removed as a way to prevent users from accidentally closing the application by accidentally double-tapping q, but this may or may not be a skill-issue

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
