### PR TITLE
add logo to linutil

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] New feature

as the tui of linutil keeps changing rapidly and new features keep getting added that make the preview outdated, i have decided to make a logo for linutil so we dont have to keep updating the preview

preview:
image

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
I kinda liked the linutil preview

**Comment by nnyyxxxx** [comment]
> I kinda liked the linutil preview

we cant keep editing that preview + the preview has to stay small which it cannot with the merge of #721

**Review by adamperkowski — APPROVED** [review]

**Comment by nnyyxxxx** [comment]
having a preview / logo that we dont have to update / maintain is for the best, and this PR achieves exactly that

**Comment by nnyyxxxx** [comment]
editing of the logo can be made in the future, its not like its a constant in any way

**Comment by pace777** [comment]
looks cool

**Pull request closed without merging**
