### PR TITLE
Fix issues with packager

### PR DESCRIPTION
**Pull request by nnyyxxxx**
# Merge with #443 #440 #454

## Type of Change
- [x] Bug fix
- [x] Refactoring

## Description
#422 does this slightly correct; I have added the missing ones that weren't included in his PR

Gaming-setup & Aur helpers were skipped due to #382 and #380 which include refactoring for both of these functionality

ONLY after I made my 3 PRs did he decide to implement MY fixes.. before: https://github.com/ChrisTitusTech/linutil/commit/61cddeb2566f0c874c15428986381832203f3591 after: https://github.com/ChrisTitusTech/linutil/commit/100fc58daa91b127187497f0061922786747db0d

My commits are VERIFIED, meaning everything that I do contains MY work. Take a look at these 2 commits and decide for your self. The first commit contained INCOMPLETE functionality and only after making my 3 PRs that fixed those issues did he decide to grab the changes in my commits and then implement them in his.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
Are you serious ?? You could have asked me to do those stuff in my PR itself !!!

Please close the new 2 competing PRs I am implementing these changes in the my PR itself

**Comment by nnyyxxxx** [comment]
> Are you serious ?? You could have asked me to make these changes in my PR itself !!!
> 
> Please close the new 2 competing PRs I am implementing these changes in the my PR itself

No thanks.

**Comment by nnyyxxxx** [comment]
@jeevithakannan2 and do not steal my ideas, I correctly implemented where you failed, and as such maybe you should close your pr??

**Comment by jeevithakannan2** [comment]
Then what about the PR https://github.com/ChrisTitusTech/linutil/pull/443

**Comment by jeevithakannan2** [comment]
And you have missed many places in this PR too

**Comment by nnyyxxxx** [comment]
> And you have missed many places in this PR too

No? I implemented it correctly, also about #443 it was made because if he accepts my versions he can't merge yours or else it will conflict so thats why it was made. I can close that PR if you want the credit for that.

**Comment by nnyyxxxx** [comment]
You'll have to close your old pull request and make a new one though.

**Comment by jeevithakannan2** [comment]
Bruh you also didn't fully finish this PR !! Maybe you should close this one

**Comment by nnyyxxxx** [comment]
> Bruh you also didn't fully finish this PR !! Maybe you should close this one

This PR is finished maybe you should tell me where its not !!

**Comment by nnyyxxxx** [comment]
gaming-setup was intentionally left out due to a rewrite in #380 if thats what you're referring to !!

**Comment by jeevithakannan2** [comment]
> > Bruh you also didn't fully finish this PR !! Maybe you should close this one
> 
> This PR is finished maybe you should tell me where its not !!

You could have done that to me told me where I have not finished it

**Comment by nnyyxxxx** [comment]
@jeevithakannan2 Not going to argue with you any longer; You're implementing the fix in areas where it does not need implemented. Such as Aurhelper, #382 . I have implemented the fix properly in these 3 PRs and yours is no longer needed, please close it.

**Review by adamperkowski — APPROVED** [review]

**Pull request closed without merging**
