### PR TITLE
UI/UX - Tabular Prototype

### PR DESCRIPTION
**Pull request by SoapyDev**
# Pull Request

## Title
Tabular Prototype - UI/UX 

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation Update (Due to be added!)
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [x] UI/UX improvement

## Description

Good day,

Here is a prototype for a tabular navigation to simplify the user experience. This prototype aim to flatten nesting structures in a scalable and intuitive way.

Addition : 
Tabs, CommandList, lots of navigation.

### Benefits 

- We can now have a welcome and help tabs dedicated to give direction and guidance to first time Linux users. 
- We avoid nesting structure that can gain complexity as time goes.
- We have a more winutil feel, that is already known and appreciated.
- We intuitively know where to put new scripts.

An emerging benefit is the separation of concerns. Application logic is separated from the view, easing new dev/sys admin that might not understand Rust into a simple and limited amount of code. 

### Inconvenient

- Need to re-implement some previously created feature .

I did try to also re-add the terminal preview, but hats off to the initial creator, its over my understanding of the current crates used by the project.  

## Testing

Only manual testing was done. 

## Impact

Added strum to the Toml as a dependency. This is also widely used by the Ratatui crate in their example.
All the previous mentioned change.

## Issue related to PR
- Resolves # https://github.com/ChrisTitusTech/linutil/issues/84

## Additional Information

Example : 

https://github.com/user-attachments/assets/3cf17eb4-4d45-4f3f-8005-542f22a65ea6

Feel free to chip, remove, take and copy/pasta as you like. As mentioned earlier, this is a prototype. I do not expect this to survive till the end of times! Style and content is only there to show how and where to add it.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by JustLinuxUser** [comment]
> We avoid nesting structure that can gain complexity as time goes.

1. you made it much much more complex on the spot
2. This issue is easily solved by creating subtrees in different files, and then just adding them to the parent node. The only reason this is not implemented in the starting implementation, is that I was not sure this was even necessary.

**Comment by JustLinuxUser** [comment]
Adding a new directory in the current implementation is roughly 5 loc, but with this aproach it seams that amount will grow significantly.

**Comment by SoapyDev** [comment]
As mentioned earlier, this is a prototype. 
Its there to show a different possibility to present things to the end user, with all the complexity, difficulties, and what else that comes with it. This is not expected to replace the current implementation, but open the discussion on an other way to do things.

1. When I spoke about the complexity, its related to how nested structure, tend to become complex as they grow. In this case we have 6 flat structure that are theme based. Scaling is done horizontally, with minimal verticallity. 
2. I agree.


Yes, I did have to rewrite almost all the app, as this is quite a different paradigm  and I could not find a way to simply reuse everything, which I would have loved as I had to write quite a lot. This is after all, my first time using Ratatui, so maybe I just passed next to an easy or not so easy way to reuse what was done. My apologies for that. 

I agree, this implementation incur a lot of boiler plate code. I am sure most of it can be improved, but I was more concerned about having a minimal viable product than reducing LOC. 

As always, thanks for your time and feedback.

**Comment by JustLinuxUser** [comment]
> As mentioned earlier, this is a prototype.
Its there to show a different possibility to present things to the end user, with all the complexity, difficulties, and what else that comes with it. This is not expected to replace the current implementation, but open the discussion on an other way to do things.

Than you did an amazing job! Thanks! I will re read your code tomorrow, and mb try working some of your ideas in the main project

**Review by ChrisTitusTech — COMMENTED** [review]
Very Cool love to see where this goes.

**Pull request closed without merging**
