### PR TITLE
refact(system-update): remove redundant DNF instructions

### PR DESCRIPTION
**Pull request by Angxddeep**
## Type of Change
- [x] Bug fix

## Description
Dnf upgrade is more than enough, dnf update is just a subset of upgrade, so there is really no need for it.

## Testing
Works

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — APPROVED** [review]
Thanks

**Comment by Angxddeep** [comment]
I always get confused between refactor and bugfix

**Comment by adamperkowski** [comment]
> I always get confused between refactor and bugfix

bugfix is fixes an issue that breaks functionality
refactor changes code in a way that COULD fix a POTENTIAL issue / benefits the codebase in some way

**Comment by jeevithakannan2** [comment]
Duplicate of #843

**Comment by adamperkowski** [comment]
@Angxddeep This does seem like a duplicate. I'll close this PR and commit your additional changes to #843

**Pull request closed without merging**
