### PR TITLE
Remove every bashism

### LINKED ISSUE #147: [Suggestion]  bluetooth
**Is your feature request related to a problem? Please describe.**
Bluetooth controller
**Describe the solution you'd like**
check out  bluetui a tui for Bluetooth coded in Rust and is using Ratatui
**Describe alternatives you've considered**
N/A
**Additional context**

### LINKED ISSUE #232: dwm not installing on debian/ubuntu
the following happens when trying to install on debian/ubuntu. Doesn't happen on Arch or fedora. Although I can't get dwm to work on fedora either. 

Screenshot (1)

### LINKED ISSUE #246: Bluetooth manager fails on ZorinOS(Debian)
## Describe the bug
Bluetooth Manager fails on Zorin OS 17.1

## To Reproduce
1. Go to 'Utilities'
2. Run 'Bluetooth manager'

## Screenshots
image

### LINKED ISSUE #312: DWM-titus on Debian fails
## Describe the bug
In the Applications Setup menu, selecting DWM-titus errors out with this:
/tmp/linutil_scripts.CNUBhPinWip7/applications-setup/dwmtitus-setup.sh: 228: Syntax error: "(" unexpected (expecting "fi")

## To Reproduce
1. Run the script using the following command: curl -fsSL christitus.com/linux | sh
2. Go to Applications Setup if not already there
3. Go to DWM-titus and hit enter
4. The error will show.

## Expected behavior
I thought it would install and configure the packages for dwm.

### LINKED ISSUE #350: Monitor settings not saving
I made a clean arch VM in QEMU, setup the entire VM using linutil and nothing else, changed my resolution to 1920x1080 using the utility and when i reboot the VM it reverts back to 1280x800

### LINKED ISSUE #383: Error when running linutil for DWM-Titus | dwmtitus-setup.sh: 228:
## Describe the bug

Error when running linutil for DWM-Titus

```
/tmp/linutil_scripts/applications-setup/dwmtitus-setup.sh: 228:
Syntax error: "(" unexpected (expecting "fi")

```

## To Reproduce
1. Use either stable or dev branch of linutil 
2. Applications Setup > DWM-Titus

## Expected behavior
Installing DWM-Titus

## Screenshots
System
Error

## Additional context
Fresh install of Debian 12 Mate Live, all packages were updated prior to trying.

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] New feature
- [x] Bug fix
- [x] Refactoring
- [x] Hotfix

## Description
I replaced every bashism with posix alternatives, I removed the custom color codes that were in almost every file (utilities), I refactored a lot of stuff (utilities), and I made it rely on the common script color codes instead of the custom ones (utilities).

## Testing
Tested on bash, zsh, and dash.

Rechecked every file using ``checkbashisms`` package

## Impact
Greatly impacts the changed sections.

## Issue related to PR

- Resolves #246 
- Resolves #147 
- Resolves #312 
- Resolves #232
- Resolves #383
- Resolves #350
- Closes #278 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
https://mywiki.wooledge.org/Bashism

Here is the site I used to squeeze out these bashisms. Might be helpful to Chris in future development.

**Comment by nnyyxxxx** [comment]
Finished, tested, and ready for review :sunglasses:

**Comment by nnyyxxxx** [comment]
@ChrisTitusTech This is going to break a lot of PRs "potentially".

**Comment by nnyyxxxx** [comment]
Just squeezed out the last bashisms out of dwm-titus. Ready for review / merge.

**Comment by nnyyxxxx** [comment]
Just squeezed out the last bashisms out of dwm-titus. Ready for review / merge.

**Comment by ChrisTitusTech** [comment]
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

**Comment by nnyyxxxx** [comment]
Finished.

**Comment by jeevithakannan2** [comment]
@nnyyxxxx Please include this issue also https://github.com/ChrisTitusTech/linutil/issues/383

**Comment by nnyyxxxx** [comment]
> @nnyyxxxx Please include this issue also #383

Thanks.

**Comment by ChrisTitusTech** [comment]
Thanks so much looks awesome @nnyyxxxx

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
