### PR TITLE
chore: Update cargo manifest

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [x] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Update `cargo.toml` manifest reflects in crates.io
- The crates were already updated in `cargo.lock` but not in `cargo.toml`
- Not that important but need to keep the records straight 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by adamperkowski** [comment]
> The crates were already updated in cargo.lock but not in cargo.toml

How did that happen?

**Comment by jeevithakannan2** [comment]
> > The crates were already updated in cargo.lock but not in cargo.toml
> 
> How did that happen?

No idea 🤷‍♂️

**Comment by adamperkowski** [comment]
Okay... What the hell. I'm seeing no diff here. Closing this.

**Comment by jeevithakannan2** [comment]
Ahh it's because chrono was removed

**Pull request closed without merging**
