### PR TITLE
fix: Remove quotes for packages

### LINKED ISSUE #688: openSUSE Tumbleweed missing packages under Build Prerequisites
## Describe the bug
The following error when running the Build Prerequisites:
'tar tree multitail tldr trash-cli unzip cmake make jq' not found in package names. Trying capabilities.                                                                             No provider of 'tar tree multitail tldr trash-cli unzip cmake make jq' found.

Are there alternative packages or a different repo to add to zypper to add those programs? I would love to have tldr, trash-cli. I am new to linux, wish I could be more help!

## To Reproduce
1. Go to 'System Setup'
2. Click on 'Build Prerequisites'
3. Scroll down to 'Let the command run'
4. See error: 'tar tree multitail tldr trash-cli unzip cmake make jq' not found in package names. Trying capabilities.                                                                             No provider of 'tar tree multitail tldr trash-cli unzip cmake make jq' found. 

## Expected behavior
Those program packages should install.

## Screenshots
ksnip_20240927-194758

## Checklist
- [X] I checked for duplicate issues.
- [X] I checked already existing discussions.
- [X] This issue is not included in the roadmap.
- [X] This issue is present on both stable and development branches.

### LINKED ISSUE #690: Arch multiple package installation using pacman/yay/paru
## Describe the bug
Build Prerequisites fails on installing packages.

## To Reproduce
1. Go to 'System setup'
2. Run 'Build Prerequisites'
3. See yay/paru error

## Expected behavior
Listed packages should be installed.

## Screenshots
image

## Additional context
I just wanna make sure this isn't happening only to me.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Remove unnecessary quotes around packages variable in compile-setup and gaming-setup.

## Testing
- Tested on arch linux works, no issues.

## Issues / other PRs related
- Resolves #690 
- Resolves #688 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by nnyyxxxx — APPROVED** [review]

**Review by adamperkowski — APPROVED** [review]

**Comment by JirakLu** [comment]
Same issue happens for `gaming-setup.sh:26`

**Comment by jeevithakannan2** [comment]
@JirakLu Ok will look into it

**Comment by cartercanedy** [comment]
@jeevithakannan2 please take a look at the files changed in #454, it looks like some arrays got quoted erroneously by @nnyyxxxx

**Comment by cartercanedy** [comment]
Might be worth running a grep over the repo to find other any other quoted arrays, as well

**Comment by nnyyxxxx** [comment]
> @jeevithakannan2 please take a look at the files changed in #454, it looks like some arrays got quoted erroneously by @nnyyxxxx

i never quoted the vars in this PR

> @jeevithakannan2 please take a look at the files changed in #454, it looks like some arrays got quoted erroneously by @nnyyxxxx

wrong

**Comment by nnyyxxxx** [comment]
there are no instances of arrays getting erroneously quoted in my PR

**Comment by nnyyxxxx** [comment]
the only vars that got quoted in my PR were packager and escalation tool, and it was suggested by Chris that i do that

**Comment by nnyyxxxx** [comment]
it's also good practice to quote vars anyways, but it depends on the context behinid those vars

**Comment by cartercanedy** [comment]
My bad, you're the first person that comes up in the git blame, so I must've misinterpreted the diffs. Either way, might be good to have your eyes on this.

**Comment by jeevithakannan2** [comment]
> @jeevithakannan2 please take a look at the files changed in #454, it looks like some arrays got quoted erroneously by @nnyyxxxx 

Yeah I will take a look at it later. I have exams this week. Will do it during my leisure time

**Comment by cartercanedy** [comment]
> it's also good practice to quote vars anyways, but it depends on the context behind those vars

Agreed, but arrays are an exception unless being used in an`eval`

**Comment by jeevithakannan2** [comment]
If it is an array it will consider it as a string with space not as arrays, that's the problem here.

**Comment by cartercanedy** [comment]
Correct, unless you're doing a string expansion inside the argument to `eval` or `exec`

**Pull request merged**
