### PR TITLE
refact: Fix all shellcheck warnings + formatting

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [x] Refactoring

## Description
- Fixes all the shellcheck warnings and formatting.
- @ChrisTitusTech I know this is a lot of file changes 99% of this is just formatting. No one was opening a PR for formatting and the shellcheck warning which causes the shellcheck workflow to fail. If you think you should do this no problem `shfmt -i 4 -ci .` at root for formatting.

## Testing
- Tested arch server setup as it has some syntax changes.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
currently you have over 20 pull requests open ! that's ridiculous, not to mention that you had 38 open at one point. Seriously..

**Comment by nnyyxxxx** [comment]
@ChrisTitusTech what are your opinions on this? i think this is just ridiculous at this point...

**Comment by nnyyxxxx** [comment]
over 80 files changed all containing useless formatting changes..

**Comment by nnyyxxxx** [comment]
as Chris would say:

"Nuke the world PR, denied."

**Comment by nnyyxxxx** [comment]
@jeevithakannan2 one question, is this tested? i assume that their is a 5% chance that you ran every script here to test your changes.

Who knows what syntax errors you could have caused in this pr.

**Comment by jeevithakannan2** [comment]
For your information shmft doesn't casues change that lead to syntax errors

**Comment by jeevithakannan2** [comment]
If you're that much worried go through the changes

**Comment by nnyyxxxx** [comment]
yeah, so what i got was that you didnt test your changes and you're currently breaking this repos COC?

**Comment by jeevithakannan2** [comment]
> yeah, so what i got was that you didnt test your changes and you're currently breaking this repos COC?

Not like you

**Comment by nnyyxxxx** [comment]
> > yeah, so what i got was that you didnt test your changes and you're currently breaking this repos COC?
> 
> Not like you

all of my recent prs have a video attached, or had one attached.

can be confirmed by Adam and other contributors. 

all of my PRs are tested as well.

**Comment by nnyyxxxx** [comment]
Listen, I'm not here trying to argue with you, but if you're going to submit a PR that practically nukes the codebase with unnecessary formatting changes and also is untested, then I will argue with you because this is practically ridiculous.

**Comment by jeevithakannan2** [comment]
See if you have a problem with too many file changes go through them to see of there is anything suspicious. And 99% of them are just formatting with shfmt there is no need for testing this. As for syntax changes arch server setup was tested.

**Comment by nnyyxxxx** [comment]
> See if you have a problem with too many file changes you can go through them to see if there is anything suspicious. And 99% of them are just formatting with shfmt there is no need for testing this. As for syntax changes arch server setup was tested.

again you're violating this repos code of conduct.

**Comment by jeevithakannan2** [comment]
> all of my PRs are tested as well.

Fixes one of your untested PR

https://github.com/ChrisTitusTech/linutil/pull/717

**Comment by adamperkowski** [comment]
please test this

**Comment by adamperkowski** [comment]
what even are those changes man? why? i'm sorry but this looks so unnecessary and pointless to me.

**Comment by adamperkowski** [comment]
why are you unquoting a var in one case but quoting the same one in another? why deleting spaces between `>` and the target? why changing var names? and there's more. it almost looks like you want to artificially pump your line count. i'm sorry but i have to close this. you can redo this PR without all those changes.

**Pull request closed without merging**
