### PR TITLE
Browser Installer Script | Competing with #498 

### PR DESCRIPTION
**Pull request by mashrukk**
# Browser Installer Script | Competing with #498 
### Installing popular browsers across various Linux distros. It currently supports the following browsers, But more browsers can be added in the future
---
### Tor Browser

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
Add quotes for variables

**Comment by mashrukk** [comment]
Suggest commits

**Comment by adamperkowski** [comment]
@mashrukk This is basically the same script as #498. You should close this and suggest the browsers in #498.

**Comment by mashrukk** [comment]
This is not copy pasting. I did things differently. This uses different browsers from your PR

**Comment by guruswarupa** [comment]
> Suggest commits

wait for my pr to get approved and then you can add as many browsers you want. you're just conflicting with my pr.

**Comment by mashrukk** [comment]
Whichever one he merges we'll both make commits to that.

**Comment by adamperkowski** [comment]
> This is not copy pasting. I did things differently. This uses different browsers from your PR

Again, the script is basically the same. This is a duplicate.

**Comment by guruswarupa** [comment]
Duplicate PR of #498

**Comment by mashrukk** [comment]
@guruswarupa My PR was completed 5 hours ago. I texted you to talk about the browser script. You didn't respond.

**Comment by guruswarupa** [comment]
> @guruswarupa My PR was complete 5 hours ago. I texted you to talk about the browser script. You didn't respond. I just got back from work and made this PR

text where?

**Comment by mashrukk** [comment]
@guruswarupa Discord

**Pull request closed without merging**
