### PR TITLE
Restructure the crates

### LINKED ISSUE #333: Crates.io & AUR packages
Hey Titus, as linutil continues to grow, I think it’s important to make it more accessible to a wider audience. One way to do this is by creating and maintaining packages for different platforms.
I'd like to offer to create and maintain the `linutil` package on [crates.io](https://crates.io) and the following packages on the [AUR](https://aur.archlinux.org):

- `linutil` - latest release built from source
- `linutil-git` - main branch built from source
- `linutil-bin` - latest binary

This includes:
For crates.io, modifying `Cargo.toml` file to meet the [requirements](https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate) (I'd open a PR), publishing the package and maintaining it.
For AUR, creating different `PKGBUILD`s for the packages and maintaining them.
Additionally, monitoring user feedback and issues on both platforms to address any concerns.
Probably updating linutil's documentation and README too, but that's up to you to decide. 

I have the knowledge and experience needed for this and it would be a pleasure for me to do it.
So, what do you say?

EDIT: 
The only issue with packaging on crates.io is that users that already have a version installed and there's a new release, don't have a "simple" way to update. https://stackoverflow.com/questions/34484361/does-cargo-install-have-an-equivalent-update-command
So I'd say installing from crates.io is not recommended.

### PR DESCRIPTION
**Pull request by adamperkowski**
# This is a big big PR. Be careful.

## Type of Change
- [x] Refactoring

## Description
Restructured the project to be more intuitive and to be able to publish on crates.io.
- Version `0.1.0` -> `24.9.19`
- Moved `tabs` dir to `core/tabs` so `linutil_core` can access it.

Resolves #333

## Testing
Compiles. Can publish.

## Additional Information
C O N F L I C T S .

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by adamperkowski** [comment]
@ChrisTitusTech This is ready to merge. There are literally no PRs open now, I'd merge ASAP. And yes, this is the only way to do this.

**Comment by lj3954** [comment]
This makes the codebase more complicated, and requires reversion if a GUI is to be developed within this repository (which is on the roadmap).

Is it not possible to include files within a parent directory within Cargo.toml?

**Comment by adamperkowski** [comment]
> Is it not possible to include files within a parent directory within Cargo.toml?

No, unfortunately it's not. Already researched it. This seems to be the only way.

**Comment by lj3954** [comment]
> I think the opposite. Now we only have one crate (`linutil`) depending on a child crate `core`. It's simplier in my opinion.

Once again, a GUI is on the roadmap. A Cargo.toml including both the data for building a binary & workspace details in one definitely also is not particularly simple.

> No, unfortunately it's not. Already researched it. This seems to be the only way.

Then, moving tabs into core will be necessary. However, moving the tui into the root directory won't accomplish anything necessary. 
Here's the note cargo gives you when you have dependencies relying on a path.
`Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.`

**Comment by nnyyxxxx** [comment]
> @ChrisTitusTech This is ready to merge. There are literally no PRs open now, I'd merge ASAP. And yes, this is the only (correct) way to do this.

dont merge this yet

**Comment by adamperkowski** [comment]
> A Cargo.toml including both the data for building a binary & workspace details in one also is not particularly simple.

I don't understand your point here. What exactly is not simple. It's done perfectly in this PR.

> Then, moving tabs into core will be necessary. However, moving the tui into the root directory won't accomplish anything necessary.

" - my personal opinion". Consider adding this to the sentence.

> Here's the note cargo gives you when you have dependencies relying on a path.

`linutil_tui` is going to be published on crates.io too. There is no other way.

**Comment by lj3954** [comment]
> " - my personal opinion". Consider adding this to the sentence.

My personal opinion is that it makes the codebase more complicated. You disagree. It's a fact that it's not a necessary change. And it's a fact that the structure **will** need to be changed once more when work on a GUI, which is on the roadmap, begins.

Yes, linutil core will be published on crates.io. That's how the TUI will be able to depend on it. What I was noting is that moving the tui outside of its own directory is not a necessity.

**Comment by adamperkowski** [comment]
> It's a fact that it's not a necessary change.

It's neccessary to do this if we want to publish the crate.

> What I was noting is that moving the tui outside of its own directory is not a necessity.

We NEED a binary target in the main crate to make this possible. `linutil_tui` is the main executable.

**Comment by lj3954** [comment]
> We NEED a binary target in the main crate to make this possible. `linutil_tui` is the main executable.

`cargo publish -p linutil_tui` would work perfectly whilst leaving TUI code in its own directory. Once again, **a GUI is on the roadmap**. A PR which makes several changes that must be reverted to begin GUI development in this repository should not be merged before those changes are dropped.

Moving tabs to core/, if necessary as you state, should occur. Versioning is also necessary, although I'm not completely sure why semver can't be used. But the last change, moving TUI into the root of the repository, must not be made.

**Comment by lj3954** [comment]
https://github.com/lj3954/linutil/commit/aabac388faac3181e5168fc458692203c6a6a779

This should fix the issue.

**Comment by adamperkowski** [comment]
> cargo publish -p linutil_tui would work perfectly whilst leaving TUI code in its own directory. Once again, a GUI is on the roadmap.

I understand that **a GUI is on the roadmap** perfectly. If we're looking at this from a GUI standpoint, your approach does make more sense. Committing the changes now.

> I'm not completely sure why semver can't be used

Chris says that he wants to stick with date versioning. I know this is a worse idea, I suggested using semver aswell.

**Comment by ChrisTitusTech** [comment]
Let me wrap my head around semver if it is better I'll figure out a way to implement it and dump my archaic date versioning.

**Review by lj3954 — APPROVED** [review]

**Review by nnyyxxxx — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
