### PR TITLE
Change wget to curl

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] New feature
- [x] Bug fix
- [x] Refactoring

## Description
Replaces wget with curl for a more flexible approach

## Testing
Works.

## Issue related to PR
- Closes #298

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by cartercanedy — CHANGES_REQUESTED** [review]
This is def a nit, but pls combine & add `-sS` flags (`curl -L -o ...` -> `curl -sSLo ...`). Make the output less verbose while also showing any errors

**Review by cartercanedy — APPROVED** [review]
Perfect :)

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

**Comment by nnyyxxxx** [comment]
> Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

Finished.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
