### PR TITLE
refact: system-update.sh

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

### Changes made to the script
- Use `nala` after installation.
- Use `nala fetch` to get the fastest mirrors.
- Removed redundant code of updates and upgrades.
- Upgrade AUR packages also.
- Simple update logic for flatpak apps.
- The old `$PACKAGER` variable in the `printf` is actually not quoted.

## Testing
- Tested on arch system and debian12 VM with no issues.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
@adamperkowski 27ac2539884a19c05021f6abb9cb51700dd01622 please revert this commit if dnf is removed from fastupdate the wild card will be called. It will exit with no suitable packages manager. The --refresh was seperated as it will be easy to debug when an error occurs. Meaning it will be easier to identify if the error occured durung refreshing the mirrors or when updating the packages.

**Comment by adamperkowski** [comment]
@jeevithakannan2 You're right here. Remember that it's your PR, you have full control over it.

**Comment by jeevithakannan2** [comment]
> @jeevithakannan2 You're right here. Remember that it's your PR, you have full control over it.

I am sure I didn't push that commit. It was authored by @Angxddeep and pushed by you.

**Comment by adamperkowski** [comment]
> > @jeevithakannan2 You're right here. Remember that it's your PR, you have full control over it.
> 
> I am sure I didn't push that commit. It was authored by @Angxddeep and pushed by you.

Yes it was. What I'm saying is you were able to revert it yourself. Sorry, should've asked you in the first place.

**Comment by jeevithakannan2** [comment]
> > > @jeevithakannan2 You're right here. Remember that it's your PR, you have full control over it.
> > 
> > I am sure I didn't push that commit. It was authored by @Angxddeep and pushed by you.
> 
> Yes it was. What I'm saying is you were able to revert it yourself. Sorry, should've asked you in the first place.

I am sorry for the hassle. I am not in my hometown and don't have my laptop with me. I am doing all the stuff with my mobile. That's why I asked you.

**Comment by adamperkowski** [comment]
> > > > @jeevithakannan2 You're right here. Remember that it's your PR, you have full control over it.
> > > 
> > > 
> > > I am sure I didn't push that commit. It was authored by @Angxddeep and pushed by you.
> > 
> > 
> > Yes it was. What I'm saying is you were able to revert it yourself. Sorry, should've asked you in the first place.
> 
> I am sorry for the hassle. I am not in my hometown and don't have my laptop with me. I am doing all the stuff with my mobile. That's why I asked you.

No problem. Was not a hassle.

**Review by adamperkowski — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
