### PR TITLE
Add wget dependency to application setups

### PR DESCRIPTION
**Pull request by jeevithakannan2**
# Pull Request

## Title
Add wget dependency to alacritty,kitty and rofi setups

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [x] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
The issue was alacritty,kitty and rofi setups failed due to wget not installed in some systems. This PR adds check for wget and installs them if not found.

## Testing
Works as expected

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
This doesn't look right.

**Review by nnyyxxxx — APPROVED** [review]

**Comment by nnyyxxxx** [comment]
There's a more flexible approach to this that doesn't require wget. I'll make a PR addressing this.

**Comment by lj3954** [comment]
I think replacing wget with curl in these scripts would be a better idea. Curl is far more widespread, and is the suggested method to launch linutil in the first place so you can almost be assured it'll be present.

**Comment by nnyyxxxx** [comment]
> I think replacing wget with curl in these scripts would be a better idea. Curl is far more widespread, and is the suggested method to launch linutil in the first place so you can almost be assured it'll be present.

Already on it.

**Comment by jeevithakannan2** [comment]
You got a point, I will close this PR

**Pull request closed without merging**
