### PR TITLE
Reduce conflicts between PRs

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] Refactoring

## Description
Reduces conflicts between PRs

This could just be used as a stepping stone; IMO it would be better if you changed all of the file names manually after finishing the 42 open PRs.

## Impact
Helps reduce conflicts between PRs

## Checklist
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
A lot of PRs are adding new files with a number in their name so there will be a lot of conflicts, this PR will remove those conflicts for future PRs.

**Comment by nnyyxxxx** [comment]
Oops, wrong button; typed that on a laptop w/ small screen :rofl:

**Comment by nnyyxxxx** [comment]
I've decided to re-open this; but this will have a lot of conflicts so be prepared.

**Comment by ChrisTitusTech** [comment]
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

**Pull request closed without merging**
