### PR TITLE
feat: Add `--skip-confirmation` flag

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Add `--skip-confirmation` flag to skip the confirmation prompt

preview

## Testing
- No issues while testing. Tested on Arch Linux

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
how exactly would this benefit user experience? they are not manually building from source, i dont see the need in this

**Comment by jeevithakannan2** [comment]
Running with `linutil` with `--skip-confirmation` will skip confirmation prompts

**Comment by nnyyxxxx** [comment]
> Running `linutil` with `--skip-confirmation` will skip confirmation prompts

not everyone are using the crates.io pkgs or the aur pkgs, we should convert this into a bind instead of relying on cli

**Comment by jeevithakannan2** [comment]
> > Running `linutil` with `--skip-confirmation` will skip confirmation prompts
> 
> not everyone is using the crates.io pkgs or the aur pkgs, we should convert this into a bind instead of relying on cli

We can have both

**Comment by nnyyxxxx** [comment]
> > > Running `linutil` with `--skip-confirmation` will skip confirmation prompts
> > 
> > 
> > not everyone is using the crates.io pkgs or the aur pkgs, we should convert this into a bind instead of relying on cli
> 
> We can have both

sgtm

**Review by adamperkowski — APPROVED** [review]
thanks

**Comment by adamperkowski** [comment]
I'll push doc changes.

**Comment by jeevithakannan2** [comment]
@adamperkowski Thanks

**Comment by jeevithakannan2** [comment]
Looks like some of the old commited PRs didn't run `cargo xtask docgen`. Will do that in a separate PR

**Comment by adamperkowski** [comment]
> @ChrisTitusTech The some of the old merged PRs didn't run `cargo xtask docgen`. Will do that in a separate PR. This PR does'nt have any issues.

#889

**Pull request merged**
