### PR TITLE
feat: Command execution log

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [x] New feature

## Description
- Add feature to save the command execution log by pressing `l` after the command execution.
- Writes the buffer to a temp file.
- The log is saved in `/tmp/linutil_log_YYYY-MM-DD-HH-MM-SS.log`

## Testing
https://github.com/user-attachments/assets/b8f3e63e-c1b1-4dd7-b5dd-a76e460e6ddf

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
Human Readable form `YYYY-MM-DD-HH-MM-SS` is used for logs rather than a unix time stamp because it is more convenient for the user.

**Comment by adamperkowski** [comment]
Well, ok. How much bigger is the binary with `time`?

**Comment by jeevithakannan2** [comment]
No crates with time stamp -> `4283240` 
crate `time` with human readable -> `4295528`
create `chrono` with human readable -> `4336488`

**Comment by nnyyxxxx** [comment]
why is this a necessary feature? i see no use in this at all

**Comment by jeevithakannan2** [comment]
Will be easier to debug script errors compared to a screen shot. Also its in the roadmap

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]
roadmap needs editing as well

**Comment by nnyyxxxx** [comment]
image
box needs checked

**Review by adamperkowski — APPROVED** [review]
@nnyyxxxx i do see how one would use this but i still think epoch would be a better idea

**Comment by jeevithakannan2** [comment]
XTasks / DocGen have nothing to do with this PR

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
