### PR TITLE
Replace remaining echo -e statement

### LINKED ISSUE #406: Bashism still exists in start scripts
#403

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] Bug fix

- Resolves #406

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by guruswarupa** [comment]
haha happens a lot of times :)

**Comment by jeevithakannan2** [comment]
Change common script line 37

`echo -e "${RED}Failed to install AUR helper.${RC}"`

**Comment by nnyyxxxx** [comment]
> Change common script line 37
> 
> `echo -e "${RED}Failed to install AUR helper.${RC}"`

No need, #382 does this already.

**Comment by jeevithakannan2** [comment]
read -s password

Will not work in wifi-control.sh line 139

**Comment by jeevithakannan2** [comment]
use 
```sh
stty -echo
read password
stty echo
```

**Comment by nnyyxxxx** [comment]
@jeevithakannan2 Should be fine.

**Comment by nnyyxxxx** [comment]
@jeevithakannan2 If you want to implement that then make a PR and gloss over the util scripts.

**Comment by jeevithakannan2** [comment]
> @jeevithakannan2 Should be fine.

read -s is not posix compliant will not work in debian 11 and 12

**Comment by jeevithakannan2** [comment]
> @jeevithakannan2 If you want to implement that then make a PR and gloss over the util scripts.

If you're creating a PR then make sure it does everything what you have described !!

**Comment by nnyyxxxx** [comment]
> > @jeevithakannan2 If you want to implement that then make a PR and gloss over the util scripts.
> 
> If you're creating a PR then make sure it does everything what you have described !!

A different PR would have to be made separate from this for every fixed script. It is 2 AM where I am at and cannot fix that issue ATM.

**Comment by jeevithakannan2** [comment]
> > > @jeevithakannan2 If you want to implement that then make a PR and gloss over the util scripts.
> > 
> > 
> > If you're creating a PR then make sure it does everything what you have described !!
> 
> A different PR would have to be made separate from this for every fixed script. It is 2 AM where I am at and cannot fix that issue ATM.

Then you should be putting this PR as draft and finish it later rather than debating with people that are doing their job

**Comment by nnyyxxxx** [comment]
> > > > @jeevithakannan2 If you want to implement that then make a PR and gloss over the util scripts.
> > > 
> > > 
> > > If you're creating a PR then make sure it does everything what you have described !!
> > 
> > 
> > A different PR would have to be made separate from this for every fixed script. It is 2 AM where I am at and cannot fix that issue ATM.
> 
> Then you should be putting this PR as draft and finish it later rather than debating with people that are doing their job

Not sure what you mean, I just recommended that this PR should be split up into multiple e.g. for every fix implemented, no need to be rude about it..

**Comment by nnyyxxxx** [comment]
I'll do this TMR when I have time.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
