### PR TITLE
Add a Linutil package installation & update script

### PR DESCRIPTION
**Pull request by adamperkowski**
## Type of Change
- [x] New feature

## Description
Added two scripts that respectively: install linutil and update it.

## Issues / other PRs related
- #333

## Additional Information
crates.io packages don't update automatically.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by adamperkowski** [comment]
oopsie

**Comment by adamperkowski** [comment]
@ChrisTitusTech This is ready to go.

**Review by nnyyxxxx — APPROVED** [review]

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]
add jq as a dep

**Comment by adamperkowski** [comment]
> add jq as a dep

No need. I'll get rid of it in the script.

**Comment by nnyyxxxx** [comment]
> > add jq as a dep
> 
> No need. I'll get rid of it in the script.

sounds good

**Review by nnyyxxxx — APPROVED** [review]
awesome

**Comment by adamperkowski** [comment]
Don't know what's up with the CI. When I ran it manually, returned no errors.
https://github.com/adamperkowski/linutil/actions/runs/10952236628/job/30410576543

**Comment by adamperkowski** [comment]
Don't know what's up with the CI. When I ran it manually, it worked.
https://github.com/adamperkowski/linutil/actions/runs/10952214271

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
