### PR TITLE
Install Paru Faster

### PR DESCRIPTION
**Pull request by mashrukk**
**Paru.git takes time to compile, while paru-bin is precompiled and installs faster.**

### CODE REVIEW

**Comment by Angxddeep** [comment]
Bro you created 4 PRs is last 4 days with the same name. Why?

**Review by nnyyxxxx — APPROVED** [review]
Thanks.

**Comment by mashrukk** [comment]
> Bro you created 4 PRs is last 4 days with the same name. Why?

For some reason it was giving errors

**Comment by nnyyxxxx** [comment]
# look at https://github.com/ChrisTitusTech/linutil/pull/382 it includes some cool refactor

**Pull request closed without merging**
