### PR TITLE
Privilages

### PR DESCRIPTION
**Pull request by dhruvmistry2000**
## Type of Change
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] New feature
- [ ] UI/UX improvement

## Description

Hey Titus I am Dhruv Mistry i have contributed in linutil and winutil both even though the contributions were small. I have done this stupid way of addressing my problem is because if i a created an issue thread it could miss. I have a concern with linutil it will to help new users to learn more about linux. With linutil you are just giving a TUI users that does most of the things for them and they wont know what they are doing and how the things happen which i don't think is your motive. I always see Vods of you live stream and in that you always say that you want everybody to learn about Linux and not just use it. I always saw you videos that motivated me to use linux as a daily driver and i have also forked some of your projects and edited them to fulfil my goal which was you main moto of making this utility. I think you should only give some basis tweaking so that the new user can start linux and after they need to find their own ways of doing different thing and this is how i learned about linux and other operating systems. For example you should remove the services as it wont help users to learn how to start enable and stop them.  This is just a small example of what i am concerned about and there are many more things that i am concerned about . 

## Issues / other PRs related

- Resolves #

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
close this pr please and make an issue, not sure what you're trying to accomplish here

**Comment by dhruvmistry2000** [comment]
I am just saying that linutil will just not help to learn new users about linux

**Comment by nnyyxxxx** [comment]
> I am just saying that linutil will just not help to learn new users about linux

then make an issue for it, this pull request is just unnecessary

**Comment by adamperkowski** [comment]
@dhruvmistry2000 You're breaking the contributing guidelines and CoC (spam). Could as well be banned from this repo. Please close this as a PR is not the place for essays. Not to mention that you didn't make **any** changes.

**Comment by dhruvmistry2000** [comment]
I am closing the PR as my concern was very wrong about this community as i though you all support learning but are just some spoon feeder who doesnt want anyone to learn more as you dont want anyone else to learn more than you all. And thanks for threating me about banning me if you want you can i dont mind

**Comment by nnyyxxxx** [comment]
> I am closing the PR as my concern was very wrong about this community as i though you all support learning but are just some spoon feeder who doesnt want anyone to learn more as you dont want anyone else to learn more than you all. And thanks for threating me about banning me if you want you can i dont mind

nobody is threatening you, your opinions are unjust, 
image
there is no point to this PR you're just adding an extra line and providing an essay that no one wants to read, if you want to provide essays then thats fine just do it in the issues section. No reason why you are making an empty PR with an essay, literally.

**Comment by dhruvmistry2000** [comment]
Can you give me chris's email ? I will just mail him and leave the thing here

**Comment by adamperkowski** [comment]
So far, this PR wasted 125 seconds of runtime = using valuable resources that **could be used for legitimate PRs that actuallt need testing**.

`contact@christitus.com`

**Comment by dhruvmistry2000** [comment]
I have closed the pr why are you bother me with msgs you could just give me the email id and leave now you have wssted 2kb og githubs storage

**Comment by adamperkowski** [comment]
FYI [64](https://github.com/ChrisTitusTech/linutil/actions/runs/11099743393)+[18](https://github.com/ChrisTitusTech/linutil/actions/runs/11099743395)+[18](https://github.com/ChrisTitusTech/linutil/actions/runs/11106784108)+[46](https://github.com/ChrisTitusTech/linutil/actions/runs/11106784115) is actually 146 seconds. I was wrong the first time, that doesn't make it any better.

**Pull request closed without merging**
