### PR TITLE
fix: DWM packages and installation bug

### PR DESCRIPTION
**Pull request by jeevithakannan2**
# Pull Request

## Title
DWM debian fixes

## Type of Change
- [x] Bug fix

## Description
- Added run time dependencies from debian12 repo https://packages.debian.org/bookworm/dwm
- Fixed a bug leading to script not executing due to package manager error
- This bug is due to checking for apt-get and not apt in the common script and using apt in the dwm script. Switching from apt to apt-get resolved the issue. 

## Testing
Tested on a new debian12 install. Working as expected

## Issue related to PR
- Resolves https://github.com/ChrisTitusTech/linutil/issues/420

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by mashrukk** [comment]
@jeevithakannan2 In DisplayManager function add xrandr and xsetroot for all package managers. If it's working on debian maybe it installs those packages with xorg and xinit. But for it's needed for pacman - xorg-xrandr xorg-xsetroot. 
I can't confirm about dnf and zypper.

**Review by mashrukk — CHANGES_REQUESTED** [review]
@jeevithakannan2 In DisplayManager function add xrandr and xsetroot for all package managers if you can. If it's working on debian maybe it installs those packages with xorg and xinit. But it's needed for pacman  xorg-xrandr xorg-xsetroot. I can't confirm about dnf and zypper.

**Comment by jeevithakannan2** [comment]
Zypper is not implemented in the script. xrandr and xsetroot packages should be added in another PR as this PR only focuses on runtime dependency fixes. If xrandr and xsetroot is used in DWM Titus I will add them here. Can you please verify whether xrandr and xsetroot are used in DWM Titus?

**Comment by mashrukk** [comment]
@jeevithakannan2  DWM Titus uses xsetroot for status bar [here](https://github.com/ChrisTitusTech/dwm-titus/blob/33fb741351755c59b0bd19a759607f5fbc8c0977/scripts/status#L55) and [here](https://github.com/ChrisTitusTech/dwm-titus/blob/33fb741351755c59b0bd19a759607f5fbc8c0977/dwm.1#L50)
I couldn't find any use of xrandr, so it may not be needed.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
