### PR TITLE
Move scripts around & refactor existing ones

### PR DESCRIPTION
**Pull request by nnyyxxxx**
# Merge #584 before this
# Merge #596 before this as well
# Merge #624  before this as well

## Type of Change
- [x] Refactoring

## Description
Moves scripts to better locations, and refactors some printf's into the if statements to prevent it from printing if the program(s) are already installed

Stop putting NEW LINES where the interactive printed message is, it just takes the user down a line, instead just use "%b" for those types of prints

## Testing
tested

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
shet

**Comment by nnyyxxxx** [comment]
wait i had local cahnges not committed yet

**Comment by nnyyxxxx** [comment]
read to go

**Comment by nnyyxxxx** [comment]
gotta fix these conflicts first

**Comment by nnyyxxxx** [comment]
all good now

**Review by adamperkowski — APPROVED** [review]

**Comment by nnyyxxxx** [comment]
doing conflicts right now

**Comment by nnyyxxxx** [comment]
DONT MERGE YET

**Comment by adamperkowski** [comment]
draft it

**Comment by nnyyxxxx** [comment]
everything fixed and in place, ready for merge

**Comment by nnyyxxxx** [comment]
checkbashisms is failing for unknown reasons just ignore it

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by nnyyxxxx** [comment]
going to fix these conflicts

**Comment by nnyyxxxx** [comment]
again lol

**Comment by nnyyxxxx** [comment]
@ChrisTitusTech all good now

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
