### PR TITLE
Use -e to keep synergy with every other script

### LINKED ISSUE #407: Use -e to keep synergy with other scripts
#405

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of Change
- [x] New feature
- [x] Refactoring
- [x] Hotfix
- [x] Security patch

## Description
No explanation needed. Ref - PR Title

- Resolves  #407

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by jeevithakannan2** [comment]
Duplicate of #388

**Comment by nnyyxxxx** [comment]
> Duplicate of #388

Not a duplicate first off, second off that was commit before this PR, and I suggested changes as well. @jeevithakannan2 You should keep your pull requests focused.

**Comment by jeevithakannan2** [comment]
Don't need to have two separate PRs for a simple change

**Comment by nnyyxxxx** [comment]
> No need of two separate PRs for a simple change

@jeevithakannan2 again you are not giving credit for that commit, I originally changed them both to -e before you committed it on yours proof? https://github.com/ChrisTitusTech/linutil/pull/388/commits/cfd6cca853a484e1d4fba0e87ca46a74d070e3f5 see here and compare dates; Add me as co-author or undo that change on your PR.

**Comment by jeevithakannan2** [comment]
Reverted as per your wish

**Comment by jeevithakannan2** [comment]
@nnyyxxxx You are wasting time and it's a simple fix, it doesn't need two separate PRs. I am not stealing your commits and I will not. I don't know why you make small things a big issue and accuse people. I am not going to argue with you over this small issue not worth my time

**Comment by nnyyxxxx** [comment]
Re-opened due to revert.

**Comment by nnyyxxxx** [comment]
> @nnyyxxxx You are wasting time and it's a simple fix, it doesn't need two separate PRs. I am not stealing your commits and I will not. I don't know why you make small things a big issue and accuse people. I am not going to argue with you over this small issue not worth my time

Never said you were, I'm only saying that this is not a duplicate, that commit that I linked was made an hour after this PR was opened with the fix.

**Review by adamperkowski — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
