### PR TITLE
DWM-Titus Install Option

### PR DESCRIPTION
**Pull request by infstate**
# Pull Request

## Title
Added install DWM-Titus feature in dot files category

## Type of Change
- [X] New feature
- [X] Bug fix
- [ ] Documentation Update (Due to be added!)
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Hello, here I have added a feature to install DWM-Titus using linutil.
To do this I created a new script called dwmtitus-setup.sh where it runs
the commands intended from the original repository.
I also added the option to the lists in the TUI.

Note: I have included my patches from my other PR.
This patch simply fixed a bug on debian based issues with APT
and is easily readable and only changes 1 - 2 lines in (src/commands/system-setup/1-compile-setup.sh).

If you do not want this patch then simply use the original setup script. (src/commands/system-setup/1-compile-setup.sh).

However, it fixes the issue of packages not found which otherwise would fail the task.
## Testing
I have tested my commits on Kubuntu 24.04 with DWM-Titus already installed.
I have not tested this on any arch based distros yet.

The commands work fine on my end.
The code is easily readable and can be adapted to work if there is any bugs that I do not know about.

## Impact
This feature can help people who want Chris Titus's workflow with DWM and automates installing it.

This feature falls under Chris-Titus's DotFiles and is optional.

Therefore people can now have his bash prompt, neovim, terminals, and DWM workflow.

## Issue related to PR
[What issue/discussion is related to this PR (if any)]
- Resolves #92 

## Additional Information
My test results may be different since I already had DWM-Titus installed.
**Also note that the script changes to the Home directory and clones DWM-Titus there.**

If you would want it to be cloned somewhere else (e.g. linuxtoolbox directory) then change the path.

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by Real-MullaC — APPROVED** [review]

**Comment by nouhtech** [comment]
I hope this option is set because I find installing DWM difficult as a beginner

**Comment by infstate** [comment]
> I hope this option is set because I find installing DWM difficult as a beginner

Yeah, It should work already with Arch and Debian Based Systems.

**Comment by ChrisTitusTech** [comment]
Love the fixes to system setup, I need to change the DWM setup script as this is doubling up the dependency installs

**Comment by infstate** [comment]
> Love the fixes to system setup, I need to change the DWM setup script as this is doubling up the dependency installs

I added a seperate PR

**Comment by infstate** [comment]
The #92 pr

**Pull request closed without merging**
