### PR TITLE
[CI Workflow] Fix pr-label

### PR DESCRIPTION
**Pull request by MyDrift-user**
## Type of Change
- [x] Bug fix

## Description

- PR's that have text formatted as code crash the workflow due to it not being read as a plain text, therefore will have syntax errors.
- switch from `pull_request` to `pull_request_target` bc of limited `GITHUB_TOKEN` permission.
- other little enhancement

## Testing

- tested again on own repo

## Issue related to PR

- Resolves issues of workflows for pr labels

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by nnyyxxxx — APPROVED** [review]
Thanks

**Review by adamperkowski — APPROVED** [review]

**Comment by MyDrift-user** [comment]
It does later on, that is just a declaration so it can easily be edited later.

Here the part:
```
if echo "$body" | grep -Eq "\- \[x\] ($pattern)"; then
              labels_to_add+=("$label")
```

**Comment by adamperkowski** [comment]
> It does later on

I was looking at a wrong file. That's why i deleted my comment.

**Comment by adamperkowski** [comment]
@MyDrift-user Check Discord.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
