### PR TITLE
Fix: config cloning

### LINKED ISSUE #664: Curl errors when installing applications
## Describe the bug
Curl errors when installing applications due to existing configs

## To Reproduce
1. Go to application setup
2. Click on applications with config cloning
3. You will see error when already existing config is found

## Expected behavior
To clone the config and work 

## Screenshots
curl-error

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Fix cloning issues.
- Curl errors sometime happens when already existing file with the same name is found.

## Testing
- No errors

## Issues / other PRs related
- Resolves #664 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — COMMENTED** [review]
I don't know if removing the backup is a good idea. We might want to prompt user which one to overwrite.

**Comment by cartercanedy** [comment]
> It's removing already existing linutilbackup. User wouldn't have a linutilbackup. Most of users rename to bak or backup and not linutilbak. So I think it won't be a problem

That check was there to prevent overwriting the users original config in the event that they run the command multiple times. I'd revert that change asap

**Comment by adamperkowski** [comment]
> So I think it won't be a problem

It most certainly would

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]
i dont approve of this at all, too many issues here

**Comment by nnyyxxxx** [comment]
image
i cant reproduce the issue you're having either.

**Pull request closed without merging**
