### PR TITLE
Fixed some Rust code structure and modified the workflow to fail if clippy returns warnings

### PR DESCRIPTION
**Pull request by adamperkowski**
## Type of Change
- [x] Refactoring

## Description
Changed the unnecessary `then` & `unwrap_or` to an if statement.
Modified the Rust workflow to fail if clippy returns warnings

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by lj3954** [comment]
Making the title variable mutable and appending the " [Multi-Select]" str afterwards  would probably be more readable.

**Comment by adamperkowski** [comment]
> Making the title variable mutable and appending the " [Multi-Select]" str afterwards would probably be more readable.

Doing it like this may be less readable but it's better for the code. `title` doesn't need to be mutable.

**Comment by lj3954** [comment]
If you want to avoid mutability, you could perhaps try something like this instead: https://github.com/lj3954/linutil/commit/8d7f2b7455b9183ab70c40d9a58a58591d4f4938.

**Comment by adamperkowski** [comment]
> If you want to avoid mutability, you could perhaps try something like this instead: [lj3954@8d7f2b7](https://github.com/lj3954/linutil/commit/8d7f2b7455b9183ab70c40d9a58a58591d4f4938).

Good idea. Thanks.

**Review by lj3954 — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
