### PR TITLE
Move mybash and CTT nvim to Linutil with minor refactoring

### LINKED ISSUE #57: Setup bash prompt aliases lack requisite packages (Debian 12)
Many aliases that replace OoB functionality in Bash have requisite packages that should be installed while setting up the ~/.bashrc. Off the _bat_, it does need `bat`, `fzf` for Zoxide, `trash-cli` and neovim installed. Might also suggest omitting aliases for other editors like nano which is perfect for simple conf files I wouldn't otherwise use nvim for.

### LINKED ISSUE #70: Neovim version compatibility is not checked when setting it up
## Describe the bug
Neovim version installed on RHEL9 using official repos (including EPFL) is 0.8* which is not compatible with the packages used for customizing nvim. Basically, setup neovim option gives an error for older versions of neovim < 0.9.4.

One error: which-key.nvim requires Neovim >= 0.9.4

## To Reproduce
1. Install RHEL9
2. run linutil > setup neovim
3. See error on first run of nvim after installation

## Expected behavior
A clear and concise description of what you expected to happen: Check if version provided by the distribution is supported.

## Screenshots
Screenshot from 2024-07-25 14-10-04
Screenshot from 2024-07-25 14-03-13

## Additional context
I used setup bash before doing this. That was the only part of linutil I used before doing this. This is also a new installation without any serious config changes and did not have nvim installed previously.
I can download nvim 0.10.* from official github repository and run it without a problem with this system.

### LINKED ISSUE #251: Kali Linux
## Not working on debian based Kali Linux
When I type source ~/.bashrc I get the following after running the "Bash Prompt" script with curl -fsSL https://christitus.com/linux | sh

```
Command 'shopt' not found, did you mean:
  command 'shout' from deb libshout-tools
Try: sudo apt install <deb name>
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
complete: command not found
_comp_dequote__initialize:unset:2: no such hash table element: 
/usr/share/bash-completion/bash_completion:615: parse error near `&'
Command 'bind' not found, did you mean:
  command 'binkd' from deb binkd
  command 'bnd' from deb bnd
  command 'bird' from deb bird
  command 'bird' from deb bird2
  command 'bino' from deb bino
  command 'find' from deb findutils
  command 'bin' from deb base-files
  command 'kind' from deb kind
  command '9bind' from deb 9mount
Try: sudo apt install <deb name>
Command 'shopt' not found, did you mean:
  command 'shout' from deb libshout-tools
Try: sudo apt install <deb name>
Command 'shopt' not found, did you mean:
  command 'shout' from deb libshout-tools
Try: sudo apt install <deb name>
Command 'bind' not found, did you mean:
  command 'bino' from deb bino
  command '9bind' from deb 9mount
  command 'bnd' from deb bnd
  command 'bird' from deb bird
  command 'bird' from deb bird2
  command 'kind' from deb kind
  command 'find' from deb findutils
  command 'bin' from deb base-files
  command 'binkd' from deb binkd
Try: sudo apt install <deb name>
Command 'bind' not found, did you mean:
  command 'bino' from deb bino
  command 'bin' from deb base-files
  command 'binkd' from deb binkd
  command 'bird' from deb bird
  command 'bird' from deb bird2
  command 'find' from deb findutils
  command 'kind' from deb kind
  command 'bnd' from deb bnd
  command '9bind' from deb 9mount
Try: sudo apt install <deb name>
Command 'bind' not found, did you mean:
  command 'find' from deb findutils
  command 'bino' from deb bino
  command 'binkd' from deb binkd
  command 'kind' from deb kind
  command 'bnd' from deb bnd
  command 'bin' from deb base-files
  command '9bind' from deb 9mount
  command 'bird' from deb bird
  command 'bird' from deb bird2
Try: sudo apt install <deb name>
Command 'shopt' not found, did you mean:
  command 'shout' from deb libshout-tools
Try: sudo apt install <deb name>

```

## To Reproduce
1. Open 'QTerminal' in Kali Linux
2. Type 'curl -fsSL https://christitus.com/linux | sh' in terminal
3. Execute 'Bash Prompt'
4. Reopen QTerminal and run 'source ~/.bashrc'

## Expected behavior
I expected the fonts to work out of the box and the fastfetch command but apparently nothing of them works.

## Screenshots
image

## Additional context

The command below is the reason why the script won't work on Kali Linux since they don't identify Kali Linux as debian using the lsb_release -a command:

┌──(ramin㉿kali)-[~]
└─$ lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2024.3
Codename:       kali-rolling

### LINKED ISSUE #265: Failed Application Setup Neovim
## Describe the bug
After setting up Neovim in the application setup, when launching neovim it tries to install the plugins and fails from not being able to resolve github.com 

## To Reproduce
1. Go to Application Setup
2. Click on Neovim
3. Let install then launch nvim

## Expected behavior
I expect gold coins to rain from the sky, no insomnia, and world peace.
Oh, and neovim to work.

## Screenshots
image

## Additional context
Here is a snippet of the above screenshot.
```
  Total: 40 plugins

  Failed (39)
    ○ alpha-nvim 
        Cloning into '/home/jeremy/.local/share/nvim/lazy/alpha-nvim'...
        remote: Enumerating objects: 1006, done.        
        remote: Counting objects: 100% (223/223), done.        
        remote: Compressing objects: 100% (96/96), done.        
        remote: Total 1006 (delta 136), reused 154 (delta 125), pack-reused 783 (from 1)        
        Receiving objects: 100% (1006/1006), 118.33 KiB | 3.38 MiB/s, done.
        Resolving deltas: 100% (248/248), done.
        fatal: unable to access 'https://github.com/goolord/alpha-nvim.git/': Could not resolve host: github.com
        fatal: could not fetch 5818065cfb64e932cebc45ed6d3819b7c3b80ca7 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
```
The rest is just like that x 39

This seems to be related to lazyvim trying to install the plugins after linutil put the configs in place and was on Manjaro.

The clone is successful, but the checkout fails. If you go into the directory its trying to do the checkout in, all the files are staged for deletion, if you reset to master/main the files show up. But then on launch they try to change to the nonexistent hash again.

### LINKED ISSUE #268: Error: Fastfetch not found
## Fastfetch not found
On Debian 12, when I select "Applications Setup" Then "Bash prompt" it starts to download stuff then I get the error "Error: Fastfetch not found", I think taht the repo should be added before trying to install it.

## To Reproduce
1. Run the script as written in the Readme: curl -fsSL https://christitus.com/linux | sh
2. Click on "Bash Prompt"
3. Error Appears

## Screenshots
image

### LINKED ISSUE #286: Neovim Fails Install -- missing packages that aren't
## Describe the bug
Selecting the Neovim install I receive the following (and is the only failure I've encountered):

The following packages are not installed:
ripgrep, fzf, xclilp, neovim, python-virtualenv, luarocks,, go, shellcheck.

NOTE:  all I did was select.

I am running Linux Mint  and verified all the listed MIA pkgs were installed, even reinstalled, then tried with remove/installed, plus rebooted, cold booted after each try -- no joy.
The only error I got from any boot was when I tred tp install Neovim.
It is probably pilot error but I don't know why or what might cause the failure.  I am guessing that with all the possible configurations that the solution would be fresh install but that would mean a new ~/ folder as keeping the could be the culprit.  That would not be acceptable for me.  
Also, I am a Neovim user but I backed my configs to a different name and a folder not in the $PATH -- no joy.
If this should bubble up to a resolution or more info, please advise.
If no NONE then I can reivew CT's code and cherry pick out what is needed to make the Neovim environment like his.  Of course that will just be a starting point for my mods (if an)...

PS---
CTL -c, CTL-x does not cancel or close the Toolbox.  Is there a graceful way to exit vs close the TAB/Termnal?

### LINKED ISSUE #295: Bash Prompt munched my .bashrc
## Describe the bug
Running the bash prompt twice ended up deleting my original .bashrc via the .bashrc.bak file not being checked if it exists already before being overwritten.

## To Reproduce
run bash-prompt script more than once (common with failures)

## Expected behavior
Ideally, number the .baks or at least check if it exists.

## Screenshots
N/A

## Additional context
FWIW this is my fault, but with the script having some problems I could see people making the same mistake, retrying after a failure and then losing their original .bashrc because it made a backup of the titus rc file that it already wrote from the first (failed) attempt, which overwrites the .bak that contains their real original .bashrc

### LINKED ISSUE #400: Add a seperate option for fastfetch and it's customization
Instead of integrating it into bash setup instead make it in it's seperate menu and add an option to add it to either zsh or bash (aka when launching terminal)

### PR DESCRIPTION
**Pull request by nnyyxxxx**
# Read everything in this PR before deciding
## Type of Change
- [x] New feature
- [x] Refactoring

## Description
~~There is 1 issue with how the cloned dir is being handled; if the folder already exists then it won't work correctly, this can be solved by adding a check to see if that path already exists and to delete it if it does. I did not know if you wanted that functionality or not so I left it out.~~ Solved with [55c6db1](https://github.com/ChrisTitusTech/linutil/pull/335/commits/55c6db1b1296025189fea4ae44cfa913b5c7e2f8)

This PR includes refactoring of the setup scripts in the original repositories to follow Posix compliant standards, I rechecked both files using the checkbashisms package to make sure.

More error handling could be added to the nvim-setup script; I have decided to refrain from doing that for now, If you do want more error handling I can make a PR tomorrow.

- About the package list: I grabbed them out of the original scripts,  I am not sure if they are correct; though I am assuming they are since they are from the original scripts.

- The neovim setup script was rewritten, and the mybash setup script was only partially rewritten. If you see something out of the ordinary in mybash then it for sure was not me.
- Review the original scripts below and compare them to the rewritten scripts before deciding on what to do with this PR.
- ref - https://github.com/ChrisTitusTech/mybash/blob/main/setup.sh
- ref - https://github.com/ChrisTitusTech/neovim/blob/main/setup.sh

## Testing
I have tested both scripts in the TUI and out of the TUI, in dash, bash, and they both work perfectly.

~~The only issue I had is listed above.~~ Solved with [55c6db1](https://github.com/ChrisTitusTech/linutil/pull/335/commits/55c6db1b1296025189fea4ae44cfa913b5c7e2f8)

## Impact
Moves both of the setup scripts over to Linutil so more contributions can be made to these 2 scripts.

## Issue related to PR

- Resolves #295
- Resolves #286 
- Resolves #268 
- Resolves #265 
- Resolves #70 
- Resolves #251 
- Resolves #57 
- Resolves #400
- Closes #328

## Additional Information
Check the description section.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by Zazucki** [comment]
thank you for this, it was my issue
https://github.com/ChrisTitusTech/linutil/issues/295

**Comment by ChrisTitusTech** [comment]
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

**Comment by nnyyxxxx** [comment]
@ChrisTitusTech Yeah I'll take a look.

**Comment by nnyyxxxx** [comment]
Ready for merge / review.

**Review by adamperkowski — COMMENTED** [review]
The code itself looks good.

> if the folder already exists then it won't work correctly, this can be solved by adding a check to see if that path already exists and to delete it if it does.

I think it's a good idea to add it (maybe ask the user for deletion or create backup) 

About other things you mentioned, @ChrisTitusTech would have to verify.

**Review by adamperkowski — APPROVED** [review]
@ChrisTitusTech, you'd have to check above (in the description)

**Comment by nnyyxxxx** [comment]
More robustness to the dir handling logic can be added later on, for now that is a starting point. :)

**Comment by cartercanedy** [comment]
Do you mind if I make a few commits related to compatibility?

**Comment by nnyyxxxx** [comment]
> Do you mind if I make a few commits related to compatibility?

Yes, if they are within good reason. Can you give examples?

**Comment by cartercanedy** [comment]
See ChrisTitusTech/mybash#89

**Comment by nnyyxxxx** [comment]
> See [ChrisTitusTech/mybash#89](https://github.com/ChrisTitusTech/mybash/pull/89)

I don't agree with those changes, you're deleting the users .bashrc.. And not creating a viable backup. Also most of that is redundant, check out this PRs file diff: It's being done much simpler.

**Comment by cartercanedy** [comment]
I don't actually do anything to the users bashrc besides append to it?

**Comment by cartercanedy** [comment]
I'm less worried about those changes and more so about the echo compat anyway

**Comment by nnyyxxxx** [comment]
> I'm less worried about those changes and more so about the echo compat anyway

@cartercanedy I'd close it until this one gets merged / reviewed / closed. Since if this one gets merged that PR won't be needed anymore

**Comment by cartercanedy** [comment]
I'm going to keep it open since it's a usability issue that should get fixed.

**Comment by cartercanedy** [comment]
I made a pr on your dev branch. I strongly believe that it should get merged if we're really on track for getting rid of bashisms entirely.

**Comment by nnyyxxxx** [comment]
> I made a pr on your dev branch. I strongly believe that it should get merged if we're really on track for getting rid of bashisms entirely.

There are no bashisms in this implementation.

**Comment by nnyyxxxx** [comment]
@cartercanedy The rest of the files that are not getting changed do include bashisms but the current scripts that are in the diff do not so I do not think it matters, though I can always merge upstream.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
