### PR TITLE
refactor: apt-get with nala and hardcoded package managers

### PR DESCRIPTION
**Pull request by jeevithakannan2**
# Pull Request

## Title
Use nala , replace hardcoded package managers, add missing checkEnv and checkEscalationTool, implement posix recommended way of using variables

## Type of Change
- [x] Refactoring

## Description
- Position nala in front in common-script so it would use nala as package manager if found
- Add nala in some missing scripts
- Replace hardcoded package managers with `PACKAGER` variable
- Added `checkEnv` in numlock for consistency among scripts
- Added `checkEscalationTool` in monitor control for consistency among scripts
- Gaming setup is not included in this PR as it is getting a rework in https://github.com/ChrisTitusTech/linutil/pull/380

## Issue related to PR 
- Closes https://github.com/ChrisTitusTech/linutil/pull/440
- Closes https://github.com/ChrisTitusTech/linutil/pull/442
- Closes https://github.com/ChrisTitusTech/linutil/pull/443

## Testing
- Tested in debian12 with nala installed works as expected.
- Tested other modified scripts in arch works as expected.

> [!CAUTION]
> The implementation of https://github.com/ChrisTitusTech/linutil/pull/440 is wrong 
> Replacing apt-get with apt is not recommended when using in scripts.
> Only if we switch nala and apt-get places in common script it will check for nala first if found it will choose nala as the package manager. 
> If not it will check for apt-get. On his implementation it will use apt itself as it checks for apt first. 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — APPROVED** [review]

**Review by nnyyxxxx — APPROVED** [review]
Thanks, you're forgetting a nala and multiple apt-gets, I've implemented them in my PR #436

**Comment by nnyyxxxx** [comment]
> # Pull Request
> ## Title
> 
> Use nala , replace hardcoded package managers, add missing checkEnv and checkEscalationTool, implement posix recommended way of using variables
> ## Type of Change
> 
>     * [x]  Refactoring
> 
> 
> ## Description
> 
>     * Position nala in front in common-script so it would use nala as package manager if found
> 
>     * Add nala in some missing scripts
> 
>     * Replace hardcoded package managers with `PACKAGER` variable
> 
>     * Added 'checkEnv' in numlock for consistency among scripts
> 
>     * Added `checkEscalationTool` in monitor control for consistency among scripts
> 
> 
> ## Issue related to PR
> 
>     * Closes [Change apt-get's & use nala along with apt | Competing with PR #422 #440](https://github.com/ChrisTitusTech/linutil/pull/440)
> 
>     * Closes [Fix issues with packager | Competing with PR #422 #442](https://github.com/ChrisTitusTech/linutil/pull/442)
> 
>     * Closes [Fix missing escalation tool | Competing with PR #422 #443](https://github.com/ChrisTitusTech/linutil/pull/443)
> 
> 
> ## Testing
> 
> Tested in debian12 with nala installed works as expected. Tested other scripts in arch works as expected
> ## Additional Information
> 
> #442 #443 are implemented after this PR with half of the my changes only. It is not completely finished. Check those two PRs with mine and decide which one to merge
> ## Checklist
> 
>     * [x]  My code adheres to the coding and style guidelines of the project.
> 
>     * [x]  I have performed a self-review of my own code.
> 
>     * [x]  I have commented my code, particularly in hard-to-understand areas.
> 
>     * [x]  My changes generate no errors/warnings/merge conflicts.

And again you're literally just putting my changes into this one @jeevithakannan2 as seen with the commits before https://github.com/ChrisTitusTech/linutil/pull/422/commits/100fc58daa91b127187497f0061922786747db0d this one was incomplete... You shouldn't lie.. 

> https://github.com/ChrisTitusTech/linutil/pull/440 https://github.com/ChrisTitusTech/linutil/pull/442 https://github.com/ChrisTitusTech/linutil/pull/443 are implemented after this PR with half of the my changes only. It is not completely finished. Check those two PRs with mine and decide which one to merge

**Comment by jeevithakannan2** [comment]
Go on and spam in other people PR's after copying theirs

**Comment by nnyyxxxx** [comment]
> Go on and spam in other people PR's after copying them

1. Did not copy you, 2. I'm competing with this PR, 3. Your PR was incomplete when I had made the other PRs, 4. The blatant lying is ridiculous when we have a commit that explains everything... Compare the dates of the creation if you want: https://github.com/ChrisTitusTech/linutil/commit/100fc58daa91b127187497f0061922786747db0d

**Comment by jeevithakannan2** [comment]
> > Go on and spam in other people PR's after copying them
> 
>     1. Did not copy you, 2. I'm competing with this PR, 3. Your PR was incomplete when I had made the other PRs, 4. The blatant lying is ridiculous when we have a commit that explains everything... Compare the dates of the creation if you want: [100fc58](https://github.com/ChrisTitusTech/linutil/commit/100fc58daa91b127187497f0061922786747db0d) before the changes: [61cddeb](https://github.com/ChrisTitusTech/linutil/commit/61cddeb2566f0c874c15428986381832203f3591)

1. If you didn't copy then how come I copied you? 2. You could have mentioned some places are missing rather than creating 3 extrta PRs 3. I didn't lie I don't remember saying I have covered all the scripts. 4. You had some places not covered before this commit 4404169e82ff774aa9d39c9f2c961e6900723c0a So that means you were lying that you covered all the scripts??

**Comment by nnyyxxxx** [comment]
> > > Go on and spam in other people PR's after copying them
> > 
> > 
> > ```
> > 1. Did not copy you, 2. I'm competing with this PR, 3. Your PR was incomplete when I had made the other PRs, 4. The blatant lying is ridiculous when we have a commit that explains everything... Compare the dates of the creation if you want: [100fc58](https://github.com/ChrisTitusTech/linutil/commit/100fc58daa91b127187497f0061922786747db0d) before the changes: [61cddeb](https://github.com/ChrisTitusTech/linutil/commit/61cddeb2566f0c874c15428986381832203f3591)
> > ```
> 
>     1. If you didn't copy then how come I copied you? 2. You could have mentioned some places are missing rather than creating 3 extra PRs 3. I didn't lie I don't remember saying I have covered all the scripts. 4. You had some places not covered before this commit [4404169](https://github.com/ChrisTitusTech/linutil/commit/4404169e82ff774aa9d39c9f2c961e6900723c0a) So that means you were lying that you covered all the scripts??

No, not exactly, I had missed those but my original implementation was correct, and BTW you shouldn't blatantly take my semi-complete fix and put it into a half baked PR.. And then start an argument over it after taking everything that was in my PR that fixed everything in this.. Here are the commits before & after you blatantly lied: before: https://github.com/ChrisTitusTech/linutil/commit/61cddeb2566f0c874c15428986381832203f3591 after: https://github.com/ChrisTitusTech/linutil/commit/100fc58daa91b127187497f0061922786747db0d

**Comment by jeevithakannan2** [comment]
Done with you do as you wish

**Comment by nnyyxxxx** [comment]
You're still missing some stuff that is correctly implemented in my 3 PRs, and you're modifying the aurhelpers when that wont be needed with #382 . Lets stop arguing over this nonsense... Just close this as its incomplete. @jeevithakannan2

**Comment by jeevithakannan2** [comment]
I don't understand what you're calling incorrect in my PR and correct in yours??

**Comment by adamperkowski** [comment]
> I don't understand what you're calling incorrect in my PR and correct in yours??

1. "_Replacing apt-get with apt is not recommended when using in scripts._" - apt overall has more features than apt-get. apt-get is "deprecated" in some distros. Why do you think it's not recommended? I recommend using apt.
2. "_On his implementation it will use apt itself as it checks for apt first._" - And what's wrong with this?
3. "_If you didn't copy then how come I copied you?_"  - ....??? You copied changes nyx made in their PRs without crediting nyx. 100fc58daa91b127187497f0061922786747db0d & 6a91e7d076ceaa33f82a702994628b6bdad04ce1 (other commits in #440 , #442 & #443 as well). Check timestamps.

Is this enough?

**Comment by nnyyxxxx** [comment]
@jeevithakannan2 Please man stop arguing with us, we have proved you wrong many times over. Just close this...

**Comment by adamperkowski** [comment]
I think #440 #442 #443 approach this better. #422 is clearly copying the changes from them into his own implementation.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
