### PR TITLE
fix: vt100 patch

### LINKED ISSUE #731: panic when scrolling
## Describe the bug
- When running a command the scrolling causes a panic.
- Turns out it is caused by a bug in vt100 https://github.com/doy/vt100-rust/pull/11

## To Reproduce
1. Run any command that outputs a very long message.
2. Press pageup 3 to 4 times.
4. See error.

## Expected behavior
- No panic and scroll up

## Screenshots
image

### Workarounds
- Limit the scroll offset up to the maximum number of rows of terminal https://github.com/ChrisTitusTech/linutil/blob/d3a801d49b6b60e92ac6f7d00b1edff211e6a721/tui/src/running_command.rs#L256
- Remove the scroll functionality for now.

### Solution
- Fork the vt100 and make our own crate just like the how other big projects are doing ( Big changes needed in linutil )
- Switching to a different parser ( Not ideal ). 

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by jeevithakannan2**
# Recommended way of doing this is mentioned in additional information

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Add vt100 patch

## Testing
- No more panics

## Impact
- Extra crate in the repo

## Issues / other PRs related
- Resolves #731 

## Additional Information
- Added the vt100 patch from https://github.com/doy/vt100-rust/pull/11
- I don't know if this is the right way to do it but the issue is fixed now.
- @adamperkowski I think doing it this way can interfere with packaging. Please look into it !!
- @ChrisTitusTech The correct way is to create a branch in linutil with only vt100 source code with the fixes and patching the vt100 in linutil cargo.toml like this

```toml
[patch.crates-io]
vt100 = { git = "https://github.com/ChrisTitusTech/linutil", branch = "vt100" }
```

- Rather than a branch a new repo would be good as cargo does not support shadow cloning ( only in nightly ), this will clone the entire history of linutil just for one crate vt100.
- A separate repository would be better if we don't want the whole linutil to be cloned for a single crate.
- If you think that is too much of a hassle, you could leave the whole bloat of the another crate in here.
- @ChrisTitusTech please go through all the above available solutions and decide. 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by adamperkowski** [comment]
This has been already discussed on Linutil's Discord server, summing it up here:

Obviously, adding 4k lines of someone else's code (without any attribution btw) is a very bad idea.
With this solution, we think Linutil should be moved to an organisation and a fork of vt100 should be created (and possibly published on crates.io) in a separate repo.

But that's 100% @ChrisTitusTech's decision. I am strongly against doing this in a branch.

**Comment by jeevithakannan2** [comment]
I agree with @adamperkowski . This PR is just to let you know the possible solutions we have it is your @ChrisTitusTech decision

**Comment by cartercanedy** [comment]
> 1. Repo & package size goes 🚀🚀🚀

Repo yes, but considering that all rust source is effectively statically linked, probably not going to affect binary size in release

Still, I agree, *_v bad_* idea to inline here

But... I *do*have half a mind to fork myself and merge some of the open PRs from doy/vt100-rust since it seems like it'd benefit more than just us

**Comment by adamperkowski** [comment]
> Repo yes, but considering that all rust source is effectively statically linked, probably not going to affect binary size in release

Never said i's going to affect binary sizes, no.
But **package sizes**, yes. [This one](https://crates.io/crates/linutil_tui).

> But... I do have half a mind to fork myself and merge some of the open PRs from doy/vt100-rust since it seems like it'd benefit more than just us

That's why I proposed creating a separate repository :))

**Comment by cartercanedy** [comment]
> With this solution, we think Linutil should be moved to an organisation and a fork of vt100 should be created (and possibly published on crates.io) in a separate repo.

Just read this :))

**Pull request closed without merging**
