### PR TITLE
Added a Search bar and organized command structure

### PR DESCRIPTION
**Pull request by afonsofrancof**
Added a Search bar and organized command structure

## Type of Change

New feature

## Description
Added a search bar to the top of Linutil.
Also, since the bash/neovim setup are technically part of your dotfiles, but were outside the folder, I decided to bring them all together into a node on the tree called "Applications Setup", which makes more sense for a normal user just wanting to set the applications up without having to worry why there are "normal" setups and your dotfiles setups.

https://github.com/user-attachments/assets/dd6a6d72-fc6c-4243-83d1-becaba666e6d

## Testing
I have tested it and everything seems to be working fine.

## Impact
If the project grew a lot, it would be hard to find the stuff we want. This makes it easier

## Additional Information
@ChrisTitusTech I thought of organizing the applications into categories folders (Terminal, shell, editor, etc) but decided I didn't want to change too much of the current structure and will leave it up to you if you want me to do it.

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by ChrisTitusTech** [comment]
That is very cool! Thanks @afonsofrancof

**Comment by afonsofrancof** [comment]
> That is very cool! Thanks @afonsofrancof 

:) 
Btw @ChrisTitusTech , feel free to change the colors of the inactive and active search bar before the merge. The grey and white I used are just placeholders cause I didn't know which ones you wanted.

**Comment by JustLinuxUser** [comment]
I would also say wait until #82 gets merged / regected, it's a bigger PR, that will change this PR a little, I know yours was first, but that one is much more global then this new feature

**Comment by afonsofrancof** [comment]
> I would also say wait until #82 gets merged / regected, it's a bigger PR, that will change this PR a little, I know yours was first, but that one is much more global then this new feature

Yup, I think not much will change, seeing as this is a completely separated widget. 
My only concert is if I then show global search results or only results from the current tab.
What do you think?
I also need to make sure that #82 will get merged before changing my branch.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
