### PR TITLE
Adding Flatpak support for "Gaming Setup"

### PR DESCRIPTION
**Pull request by sevu11**
# Pull Request

## Title
Adding support for Flatpak and Flathub during `Gaming Setup` option. 

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
It will install Flatpak and setup repo if needed. DNF is skipped as it already come shipped.
On Debian 12 it will configure backend dependencies for Store front, depending if user uses Gnome or KDE.

## Testing
Tested in both VMs and Distrobox. I have not encountered any issues.

## Issue related to PR
- Resolves https://github.com/ChrisTitusTech/linutil/issues/290 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
This should be made It's own option and named "Flatpak setup" instead of putting it in the gaming setup, not everyone will want flatpak being installed + It seems out of place to include in gaming setup.

**Comment by kleidis** [comment]
We opened a PR with the same goal, lol in a spam of 20 minutes

https://github.com/ChrisTitusTech/linutil/pull/341

**Comment by sevu11** [comment]
> We opened a PR with the same goal, lol in a spam of 20 minutes
> 
> #341

Sometimes life is funny. I'll close mine.

**Comment by sevu11** [comment]
> This should be made It's own option and named "Flatpak setup" instead of putting it in the gaming setup, not everyone will want flatpak being installed + It seems out of place to include in gaming setup.

That's fair. Good point, Nyx.

**Pull request closed without merging**
